### ISSUE TITLE
Scancode fails to detect copyright and license information in source files

### ISSUE THREAD

**Issue by majurg** [nexB/scancode-toolkit#107]
On the latest development branch scancode fails to pick up the copyright `Copyright (C) <2013>, GENIVI Alliance, Inc.`, and the license `Mozilla Public License (MPL), v. 2.0.`

The `./scancode` command was run over the Github repository https://github.com/Arynga-Open-Source/CIVG 

The offending files are located here: https://github.com/Arynga-Open-Source/CIVG/tree/master/modules/downloader/dumm_downloader/dumm/src

The files in question: 

```
curl-httpheaders.h
main.cpp
mgr-commoni.h
mgr-download.cpp
mgr-download.h
mgr-downloadi.h
mgr-upload.cpp
mgr-upload.h
mgr-uploadi.h
obj-common.cpp
obj-download.h
obj-upload.cpp
obj-upload.h
```

**Comment by pombredanne** [comment]
The pattern seem to be that the year is enclosed in <brackets> as in `Copyright (C) <2013>, GENIVI Alliance, Inc.` and the year range is not recognized by the parser.

**Comment by balusarakesh** [comment]
issue with the license is fixed

**Comment by pombredanne** [comment]
There are still incorrect detections related to this ticket which I will fix now

**Comment by pombredanne** [comment]
In particular an LGPL-3.0 was detected an LGPL 2.1

**Comment by pombredanne** [comment]
This has been fixed in #790 Thanks for the report!
