### ISSUE TITLE
Install scancode resulting in ERROR: Could not build wheels for intbitset, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by NaveenTSW** [nexB/scancode-toolkit#3144]
### Description

Error when installing scancode-toolkit
error: legacy-install-failure
 Encountered error while trying to install package.
╰─> intbitset

Tried adding explicit wheel installation " pip install scancode-toolkit --use-pep517" this also complains about intbitset 
### How To Reproduce

> Tell us how to reproduce the issue. 
Using below commands in github action to install scancode-toolkit results in error, could not build wheels for intbitset

python -m pip install --upgrade pip 
pip install scancode-toolkit 

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Linux)
* What version of scancode-toolkit was used to generate the scan file? latest 
* What installation method was used to install/run scancode? (pip/source download/other) pip install scancode-toolkit

**Comment by pombredanne** [comment]
@NaveenTSW  Thanks for the report!

Can you tell which exact Linux distro, processor architecture and Python version you use?

And also: did you follow the installation instructions, in particular the pre-requisite at https://scancode-toolkit.readthedocs.io/en/latest/getting-started/install.html#install-prerequisites ?

Note that if you do a pip installation you may need a compiler toolchain and the development version of the dependencies.

**Comment by NaveenTSW** [comment]
@pombredanne Thanks for the quick response

Linux distro - Ubuntu
 20.04.5 LTS
Python version - 3.x, using github action and can see setup CPython (3.11.0) successfull

have been using only below commands as part of the github actions, from past 6+ months it was working all fine and started erroring out from 2nd November 2022.

 python -m pip install --upgrade pip
 pip install scancode-toolkit

**Comment by tdruez** [comment]
@NaveenTSW `intbitset` is not yet supported on Python 3.11, see https://github.com/inveniosoftware/intbitset/issues/81

**Comment by pombredanne** [comment]
ok, I maintain intbitset too, so let me see what we can do there.

**Comment by NaveenTSW** [comment]
@pombredanne any updates on this ?

**Comment by sschuberth** [comment]
Apparently the issue was fixed in intbitset, but no new intbitset release with the fix was made yet.

**Comment by pombredanne** [comment]
@sschuberth good point... let me push this release there!

**Comment by pombredanne** [comment]
I released macOS fat binary wheels for https://github.com/inveniosoftware/intbitset/ and https://github.com/WojciechMula/pyahocorasick in the last few days.

Could you test if these pre-built binaries work on your machine with a pip install?

**Comment by sschuberth** [comment]
Maybe also @MarcelBochtler could help testing.

**Comment by michaeldorner** [comment]
Thanks for looking into the issue. As far as I can tell, this issue is still around.
