### ISSUE TITLE
Unhandled exception in _runner

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#521]
This is what I'm getting with ScanCode db5f6eb:

    Unhandled exception in thread started by <function _runner at 0x7f0f27e99ed8>
    Traceback (most recent call last):
      File "scancode/src/scancode/interrupt.py", line 74, in _runner
        res = func(*args, **kwargs)
      File "scancode/src/scancode/cli.py", line 575, in scan_one
        for scan_name, scan_func in scanners.items():
      File "/usr/lib64/python2.7/collections.py", line 127, in items
        return [(key, self[key]) for key in self]
      File "/usr/lib64/python2.7/collections.py", line 97, in __iter__
        curr = curr[1]                              # move to next node
    Exception

**Comment by pombredanne** [comment]
@sschuberth Thanks for the report. Is this all you get? 

Likely unrelated I am getting some weird heisen test failures on Travis atm that I have trouble to trace down.

**Comment by pombredanne** [comment]
@sschuberth Anything extra to help reproduce this? which scan options where you using? any public test file that would exhibit the same issue?

**Comment by sschuberth** [comment]
There's no more than that in the output, but I get these a ton of times. Command line used is `scancode --copyright --license --package --info --diag --only-findings --strip-root --timeout 300 -n 2 -f json . results.json`. I'll see if there's a public repo to reproduce.

**Comment by sschuberth** [comment]
@pombredanne Any idea which commit might have introduced this so I can temporarily revert it?

**Comment by pombredanne** [comment]
@sschuberth The last stable build in the CI is e339571 https://travis-ci.org/nexB/scancode-toolkit/builds/205610589

**Comment by pombredanne** [comment]
@sschuberth have you tried with a clean clone in a different directory?

**Comment by pombredanne** [comment]
@sschuberth I cannot find a way to reproduce here, using the HEAD of `develop`

**Comment by pombredanne** [comment]
@sschuberth if you want wee could have a quick screen sharing session with uberconference.

**Comment by sschuberth** [comment]
Thanks for the offer but I am on my way home from the office currently. My feeling is this only happens if the machine is under heavy load. While we only use `-n 2`, we run several separate invocations in parallel.

**Comment by pombredanne** [comment]
@sschuberth This does not feel right and I would like to get to the bottom of it. I am available anytime so we can fix this.

**Comment by pombredanne** [comment]
@sschuberth could it be that you updated the code to a newer version while you had processes running with the older version? This could eventually lead to some weird cases I guess especially with the license cache.

**Comment by sschuberth** [comment]
Not really. The different invocations run in isolated workspaces, and in each a `git clean -fdx` is done in the beginning.

**Comment by pombredanne** [comment]
hum, let me see if I can add some logging/tracing enabled with `--diag` even if temporarily in a branch

**Comment by sschuberth** [comment]
More similar stack traces:

    01:57:07.817 Scanning files...
    02:01:25.843 Unhandled exception in thread started by <function _runner at 0x7f457fae8de8>
    02:01:25.843 Traceback (most recent call last):
    02:01:25.843   File "/var/lib/jenkins/jobs/scancode/workspace/tools/scancode/src/scancode/interrupt.py", line 75, in _runner
    02:01:25.843     results.put(res)
    02:01:25.843 Exception
    02:04:46.860 Scanning done.

    03:25:24.479 Scanning files...
    03:31:53.375 Unhandled exception in thread started by <function _runner at 0x7f01637df230>
    03:31:53.375 Traceback (most recent call last):
    03:31:53.375   File "/var/lib/jenkins/jobs/scancode/workspace/tools/scancode/src/scancode/interrupt.py", line 75, in _runner
    03:31:53.375     results.put(res)
    03:31:53.375   File "/usr/lib64/python2.7/Queue.py", line 140, in put
    03:31:53.375     self.not_full.release()
    03:31:53.375 Exception
    03:42:21.874 Scanning done.

**Comment by pombredanne** [comment]
@sschuberth could you try a test scan using the code in the `521-trace-threading` branch? it should print out more details of the failure.

**Comment by sschuberth** [comment]
I'm giving it a try now, however I can only use our staging environment for this, and in there I've not yet seen the issue anyway, only in production :-(

**Comment by pombredanne** [comment]
@sschuberth these kind of heisenbug are a pita, are they? What can I do to help your testing in production?

**Comment by pombredanne** [comment]
@sschuberth are the OSses/arch and python versions the same on staging and prod?

**Comment by pombredanne** [comment]
and the installed OS packages too?

**Comment by pombredanne** [comment]
May be a VM with limited resources could help to reproduce ? Is there a public piece of code that chokes systematically? or is this random? The only thing I can think of being a culprit would be in there: https://github.com/nexB/scancode-toolkit/commits/develop/src/scancode/interrupt.py

**Comment by sschuberth** [comment]
Thanks a lot for your willingness to help, but I fear there's not much you can do right now. I'm trying to retrigger a bunch of jobs, and we'll simply have to wait for the outcome.

Arch and Python versions are the same, but production is a VM, and staging is a bare metal machine. So indeed a VM with limited resources could help to reproduce the issue...

**Comment by sschuberth** [comment]
I can reproduce it in staging now (which is a bare metal machine running Ubuntu 16.04.02 LTS, 64-bit, with Python 2.7.12). I'm running two scans with `scancode --copyright --license --package --info --diag --only-findings --strip-root --timeout 300 -n 10 -f json .` each in parallel, and that triggers:

    00:45:54.058 Scanning files for: infos, licenses, copyrights, packages with 10 process(es)...
    00:45:54.058 Building license detection index...Done.
    00:45:56.142 Scanning files...
    00:46:33.626 Unhandled exception in thread started by <function _runner at 0x7f03a6a11938>
    00:46:33.638 Traceback (most recent call last):
    00:46:33.638   File "/home/jenkins/jobs/scancode/workspace/tools/scancode/src/scancode/interrupt.py", line 88, in _runner
    00:46:33.640     results.put(res)
    00:46:33.640   File "/usr/lib/python2.7/Queue.py", line 140, in put
    00:46:33.649     self.not_full.release()
    00:46:33.654 Exception
    00:47:48.979 Scanning done.

Unfortunately, there seems to be no additional info from the changes in your branch (which I've merged).

**Comment by pombredanne** [comment]
excellent. Any special scanned files that triggers this? of anything goes?

**Comment by sschuberth** [comment]
I'm not currently running with `--verbose` to the see files, but I'll do now. I'll also decrease the timeout to `--timeout 30` to see if it happens for files were the timeout is exceeded.

**Comment by sschuberth** [comment]
So, after turning on `--verbose` I cannot see any pattern behind the files it's failing for:

```
02:44:59.777 Scanned: spring-websocket/src/main/java/org/springframework/web/socket/server/support/HttpSessionHandshakeInterceptor.java
02:44:59.777 Scanned: spring-websocket/src/main/java/org/springframework/web/socket/sockjs/transport
02:44:59.782 Unhandled exception in thread started by <function _runner at 0x7fb60441b320>
02:44:59.782 Traceback (most recent call last):
02:44:59.782   File "/home/jenkins/jobs/scancode/workspace/tools/scancode/src/scancode/interrupt.py", line 88, in _runner
02:44:59.805     results.put(res)
02:44:59.805 Exception
02:44:59.841 Scanned: spring-websocket/src/main/java/org/springframework/web/socket/sockjs/SockJsException.java
02:44:59.841 Scanned: spring-websocket/src/main/java/org/springframework/web/socket/sockjs/SockJsMessageDeliveryException.java
```

**Comment by sschuberth** [comment]
Also, what's a bit annoying is that is does not tell *which* exception is actually being thrown. Could we change that?

**Comment by pombredanne** [comment]
Well I wished I knew what is happening but exceptions in multithreaded code are sometimes hard to get to.

Now at least I have enough to try reproduce this: 
- System: Ubuntu 16.04.02 LTS, 64-bit, with Python 2.7.12
- test archive: this directory https://github.com/spring-projects/spring-framework/tree/master/spring-websocket/src
- command: `scancode --copyright --license --package --info --diag --only-findings --strip-root --timeout 300 -n 10 -f json .`

**Comment by pombredanne** [comment]
@sschuberth I will be spinning a VM with this: 
`ubuntu-16.04.2-server-amd64.iso`

**Comment by sschuberth** [comment]
Sounds good, let me know if you manage to reproduce it. Note that I had to launch `scancode --copyright --license --package --info --diag --only-findings --strip-root --timeout 300 -n 10 -f json .` at least two times in parallel to trigger this.

**Comment by pombredanne** [comment]
@JonoYang You are running Ubuntu 16.x on your laptop if I recall? Would you mind doing a quick test on this too? I will run a VM test today with virtualbox on my side. But I could not reproduce on Ubuntu 14.04.x desktop on my laptop. .... 
@sschuberth I will push also a CI test. But the Travis CI machines run on Ubuntu 12.04.x and my hunch is that there is something specific about the combo of OS and Python version and possibly a Python bug.

**Comment by JonoYang** [comment]
@pombredanne  Using both the develop branch and commit `db5f6eb`, I have ran ScanCode on https://github.com/spring-projects/spring-framework/tree/master/spring-websocket/src with the command `scancode --copyright --license --package --info --diag --only-findings --strip-root --timeout 300 -n 10 -f json .` and I was unable to reproduce the error.

**Comment by sschuberth** [comment]
Note that I also needed to run scancode with that command line at least two times in parallel (and with `-n 10` each), e.g. different terminal windows, to see the exception.

**Comment by JonoYang** [comment]
@sschuberth I have reran the test using two terminal windows and I could not reproduce the issue. Am I missing something?

**Comment by sschuberth** [comment]
Probably not, it's simply hard to reproduce. I also only see it occasionally in scan that last > 30 mins and create a lot of CPU / IO load.

**Comment by pombredanne** [comment]
I am trying to get to the bottom of this.... But I was not yet able to reproduce :|

**Comment by sschuberth** [comment]
Thanks for your continued effort to help resolving this. BTW, I don't think it's too much related to Ubuntu 16.04 in particular, because I see the same thing on Amazon Linux in an AMI. The only thing that's common is Python 2.7.12.

**Comment by pombredanne** [comment]
@sschuberth thanks that a super useful input.

**Comment by pombredanne** [comment]
The only I get atm with two runs in // of `./scancode --copyright --license --package --info --diag --only-findings --verbose --strip-root --timeout 10 -n 10 -f json-pp tests/` on a Ubuntu 16 server VM with 2Gb of rAM allocated is this:


`Traceback (most recent call last):
  File "/home/pombredanne/scancode-toolkit/bin/scancode", line 11, in <module>
    load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
  File "/home/pombredanne/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/pombredanne/scancode-toolkit/src/scancode/utils.py", line 64, in main
    standalone_mode=standalone_mode, **extra)
  File "/home/pombredanne/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/pombredanne/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pombredanne/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/pombredanne/scancode-toolkit/src/scancode/cli.py", line 293, in scancode
    strip_root=strip_root)
  File "/home/pombredanne/scancode-toolkit/src/scancode/cli.py", line 395, in scan
    result = scanned.next()
  File "/home/pombredanne/scancode-toolkit/local/lib/python2.7/site-packages/click/_termui_impl.py", line 240, in next
    rv = next(self.iter)
  File "/home/pombredanne/scancode-toolkit/src/scancode/pool.py", line 47, in wrap
    return func(self, timeout=timeout or 1e10)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
thread.error: can't start new thread
``

**Comment by pombredanne** [comment]
@sschuberth how many processors are enabled on these VMs? and how much RAM allocated?

**Comment by pombredanne** [comment]
@sschuberth after careful consideration and chat discussions with some expert Pythonista, I will push a new design that uses only processes and drops using threads entirely. This is the only sane way. ETA tomorrow.

**Comment by sschuberth** [comment]
> how many processors are enabled on these VMs? and how much RAM allocated?

Sorry for not answering that earlier. The AWS instance is a [m3.xlarge](https://aws.amazon.com/ec2/instance-types/) one, so 4 CPUs and 15 GB of RAM. But like I said, I can reproduce the same thing in a bare metal machine with 12 CPUs and 12 GB of RAM.

> I will push a new design that uses only processes and drops using threads entirely.

Just curious, what's wrong with threads in Python?

**Comment by pombredanne** [comment]
>Just curious, what's wrong with threads in Python?
They cannot be killed cleanly short of a hack I committed in `src/scancode/thread2.py`
And they run one at a time in most cases in a given process because of the Python global interpreter lock. So this makes them poor parallelization primitives in the general case when using Python.

In our special case where we want to both kill on certain limits (time, ram) and be truly parallel they end up having none of the ideal qualities we would want. In contrast, killing a process is always a clean event. RAM can only be seriously monitored at the process level too, never at the thread level. So mixing the two is not a great idea after all IMHO and a very likely source of the problems you face.

Beside this, there are bugs that seem to exist in some combo of  Python2 version and OS and not some other. But not in a consistent fashion which makes it a hair puller when considering Windows, macOS and Linux on so ~ 8 to 10 Python 2.7 dot version variations.

**Comment by pombredanne** [comment]
So after more chats with threading experts, the issues stem likely from using `multiprocessing` and not from `threading`: therefore the route I am taking now is:
1. an outer thread pool if possible NOT using `multiprocessing` but may be `billiard` or something else.
2. each thread will: 
2.1. spawn a standard `subprocess` that will do its bidding and importantly write to cache (or to a defined temp file) directly, returning only a minimal return code and error information in  stdout/stderr. This means bypassing `pickle` which is at the heart of many `multiprocessing` problems I am faced with. 
2.2. once the `subprocess` is started, the thread will run a sentinel loop to guard to excessive time and memory usage and kill the `subprocess` as needed if any of these is exceeded.

This will require a little bit of refactoring  but goes in a preferred direction: I want plugins to be writable in any programming language and therefore they will be always spawned in their own subprocess. So what we can do for Python here will benefit a future plugin architecture.

**Comment by pombredanne** [comment]
@sschuberth do you mind to check out the code in this new branch? https://github.com/nexB/scancode-toolkit/tree/cache-lock 
This is a separately reported problem by https://github.com/Linutronix/ but this is quite likely to be closely related to yours. The fix is only with new updated locking libraries.

**Comment by sschuberth** [comment]
I gave the *cache-lock* branch (9be63735625d19cdc2486a654b701217144a3a49) a try over night, but you won't like the answer:

```
01:31:56.632 Scanning files...
01:34:51.519 Unhandled exception in thread started by <function _runner at 0x7f9d5c971b90>
01:34:51.519 Traceback (most recent call last):
01:34:51.519   File "/home/jenkins/jobs/scancode/workspace@3/tools/scancode/src/scancode/interrupt.py", line 75, in _runner
01:34:51.536     results.put(res)
01:34:51.536 Exception
01:36:20.801 Scanning done.
```

This is again on our staging bare metal machine.

**Comment by pombredanne** [comment]
@sschuberth Thanks. I like it. This is useful.

**Comment by pombredanne** [comment]
@sschuberth I pushed something that looks quite stable so far to the `521-trace-threading`. This is not the final solution yet but I hope it should fix your bug. You will note that I removed entirely the max memory sentinel which is likely part of the problem.

**Comment by sschuberth** [comment]
Ok, I've triggered again some scans. Let's see what their logs say tomorrow!

**Comment by sschuberth** [comment]
@pombredanne There's some improvement with branch *521-trace-threading* (91a553057f26e43f5f125aa9266a44bd50dc63ca ) it seems. I still see

```
23:41:54 Scanning files...
23:43:54 Unhandled exception in thread started by <function _runner at 0x7fd68a93bde8>
23:43:54 Traceback (most recent call last):
23:43:54 File "/home/jenkins/jobs/scancode/workspace/tools/scancode/src/scancode/interrupt.py", line 66, in _runner
23:43:54 results.put(func(*args, **kwargs))
23:43:54 Exception
23:46:24 Scanning done.
```

But I see this only once where previously I was seeing this about eight times.

**Comment by pombredanne** [comment]
@sschuberth thanks. I am working on yet another implementation that gets rid entirely of using queues (and any possibly pickling that may happen behind the scenes)

**Comment by pombredanne** [comment]
@sschuberth I am pushing this new implementation today.... so you could try it tomorrow.

**Comment by pombredanne** [comment]
@sschuberth This should be ready for you to test now.

**Comment by pombredanne** [comment]
Note that I am now using signals on posix and threads on Windows, using a well tested implementation of timeouts from the robotframework by @pekkaklarck and @mkorpela 
Things should be also faster on posix as a result of this.

**Comment by pekkaklarck** [comment]
That timeout code is mainly implemented by @mkorpela. Works surprisingly well considering how complicated the domain is. Really cool that it used externally! Can you @pombredanne share where/how you've used it? Perhaps @mkorpela and I could package the useful bits into a separate module outside Robot Framework.

**Comment by sschuberth** [comment]
@pombredanne I'm giving branch *521-trace-threading* another try now!

**Comment by sschuberth** [comment]
@pombredanne This is looking good now actually! No more unhandled exceptions in the logs anymore fo rthe use-case where I previously saw plenty of them! 👍

**Comment by pombredanne** [comment]
@sschuberth Thanks. I need to refine a failing tests and we should back in business. Sorry it took so long... but this was a pesky one.

**Comment by pombredanne** [comment]
@pekkaklarck @mkorpela I reused your posix and windows timeout implementation here: https://github.com/nexB/scancode-toolkit/tree/521-trace-threading/src/scancode/timeouts

It would be great to have the directory packaged separately. One simple approach is to add a timeout_setup.py that would just handle the packaging for this.... or a separate repo. Your call!
and thanks++ in anycase.

**Comment by sschuberth** [comment]
@pombredanne Any update on when this will land in `develop`? We're seeing a lot of the unhanded exceptions currently, and it's unclear how many findings we're missing because of this.

**Comment by pombredanne** [comment]
@sschuberth I am merging this today :)

**Comment by pekkaklarck** [comment]
@pombredanne This sounds like a good reason to sit down and have few beers with @mkorpela. We could try making the code fully independent on Robot and put it into PyPI one way or the other.

**Comment by pombredanne** [comment]
@pekkaklarck :beer: and :beers: would be great! Alas we may need to settle for the virtual kind for now as we may not exactly be in the same locale...
My simpler approach would be to add a `setup.py` and related minimal files to also package this subset as its own separate Pypi lib. With this you would have a nice combo: no explosion of smaller repos that creates additional coordination work on your side AND the ability to consume this code subset as a lib for the rest of us.

**Comment by sschuberth** [comment]
> I am merging this today :)

Just checking: That "today" did refer to yesterday, right? 😜

**Comment by pombredanne** [comment]
@sschuberth today is still today for me, as I am 8 hours behind you atm... and I was side tracked by some major bugs elsewhere.

**Comment by sschuberth** [comment]
@pombredanne Ah, sorry. I thought you're in France these days!

**Comment by pombredanne** [comment]
@sschuberth CA atm ;)

**Comment by pombredanne** [comment]
@sschuberth This is merged now. I still need to refine one test, but this can wait until tomorrow.

**Comment by pombredanne** [comment]
note that I meant to squash the commit, but the history on such pesky issue has some value ... so I decided to leave the commit stream as-is.

**Comment by sschuberth** [comment]
> I was side tracked by some major bugs elsewhere.

Does "elsewhere" mean "outside of ScanCode"? IOW, are you aware of another major issue in ScanCode currently, or do you consider it somewhat safe to use the *develop* branch right now?

**Comment by pombredanne** [comment]
@sschuberth yes, that was outside of scancode alright :) The develop branch is stable and is the one that I use all the time otherwise
Actually this is reaching the point where we need to cut a 2.0.0 at last now. Likely a job for tomorrow.

**Comment by pekkaklarck** [comment]
@pombredanne Was thinking about :beers: with @mkorpela, we live in the same city, but we'll raise a glass for you if/when that happens. =)

**Comment by mkorpela** [comment]
After having enough of 🍻 I think all these timezone problems can be resolved :D

**Comment by sschuberth** [comment]
I'm not seeing this anymore since the merge of *521-trace-threading* to *develop*, so I'm closing. Thanks @pombredanne for the good job!

**Comment by pombredanne** [comment]
This is fixed for good now!

**Comment by sschuberth** [comment]
Confirmed, I also haven't seen this in a long time! Thanks again!

**Comment by pombredanne** [comment]
@sschuberth 
> Does that commit affect the "Some files failed to scan properly. See scan for details" error that I get once and then if the per-file scan timeout is exceeded?

It does not affect it in the sense that the behaviour should be the same. The code is just cleaner and tighter and there were a few corner cases that choked, especially on windows
